TEMPLATE = {
    "0_INBOX": {"file_extensions": ""},
    "1_ARCHIVES": {"file_extensions": ["zip"] },
    "Apps/Linux": {"file_extensions": ["deb"]},
    "Apps/Windows": {"file_extensions": ""},
    "Documents": {"file_extensions": ""},
    "Music": {"file_extensions": ""},
    "OS_ISO": {"file_extensions": ""},
    "Audiobooks": {"file_extensions": ""},
    "Photos": {"file_extensions": ""},
    "Pictures/Wallpapers": {"file_extensions": ""},
    "Pictures/funny": {"file_extensions": ""},
    "Backups": {"file_extensions": ""},
    "Video": {"file_extensions": ""},
}
